### ISSUE TITLE
The PEP should describe giving types for *args, **kwds

### ISSUE THREAD

**Issue by gvanrossum** [ambv/typehinting#139]
This is supported in the annotation syntax, it would be nice if the PEP declared how you should use it.
```
def foo(*args: int, **kwds: float) -> None: ...
```
This specifies that each positional argument must be an int and each keyword argument must be a float. The actual type of args and kwds in the function body are something like Sequence[int] and Dict[str, float]. Note that the key type of kwds is not given since it is always string (enforced by the language).

**Comment by NYKevin** [comment]
The answer to this question is probably "use `Any`," but I'd like to ensure people are aware of it in the first place.

I have objects with `__init__` that looks (vaguely) like this:

    class Foo:
        def __init__(self, **kwargs):
            for name, value in kwargs.items():
                if name in self.fields():
                    # if we magically know there is a descriptor 
                    # by that name attached to the class
                    setattr(self, name, value)

Since the values are of heterogenous types, this means I'll need to use `**kwargs: Any`.  Since I can't think of any reasonable way of describing the types (not even using e.g. `Union[]`), that's probably the only sane design here anyway.

In my case, the recognized `name`s correspond directly to descriptors attached to the class, which have proper type hints.  If/when descriptor support is added, it would be nice to have stricter type safety on these arguments.  I'm not sure how that could be achieved, though.  I can't just use generics, at least not without variadic generic support (yikes).

**Comment by gvanrossum** [comment]
But this is not unique to `**kwds` is it? It's just the case that the values of kwargs don't have a homogeneous types, and in any such situation you'll need to fall back on `Any`. IIRC the PEP *does* explain what the annotation for `*args` and `**kwds` mean -- `*args: t` implies that `args` is a `List[t]` and `**kwds: t` implies that `kwds` has type `Dict[str, t]`.

**Comment by NYKevin** [comment]
Yes, I agree.  I'm just whining that there's no way to say "these kwargs correspond to those attributes 1:1", which feels like a fairly common design pattern.

**Comment by gvanrossum** [comment]
But the pattern is explicitly dynamic, which means trying to type-check is pretty much off the table. If you want it type-checked you should use a less dynamic pattern. :-)
