### ISSUE TITLE
should "x or y or z" be parsed as Union[] in pyi?

### ISSUE THREAD

**Issue by matthiaskramm** [ambv/typehinting#174]
Since `pyi` files need to be valid Python syntax, but are only processed through special tools, it would be possible, from an implementation standpoint, to allow

```x or y or z```

as an alternative to

```Union[x, y, z]```

.

Should the former be allowed? I'm torn. I think the former looks more nice, but it also means that pyi and inline PEP 484 would use different conventions.

**Comment by gvanrossum** [comment]
I'm pretty sure this was one of the many alternatives brought up for PEP
484. For inline annotations it can't work because of the hard-coded
shortcut semantics of 'or'. I'd rather not add unnecessary variation to
stub syntax -- there are some specific differences but they are all
*needed* (e.g. not automatically re-exporting imported names, relaxed
forward referencing rules). With this proposal we'd also run into trouble
when people copy/paste annotations from stubs to inline.

**Comment by matthiaskramm** [comment]
Ok. Good point about copy/paste from py to/from pyi. I'll close this issue.
