### ISSUE TITLE
TypeVar example in PEP is confusing

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#39]
[I think Guido pointed this out elsewhere, but maybe this should be addressed separately here so that it won't be forgotten.]

The following type variable constraint example from the PEP is confusing:

    from typing import Iterable
    X = TypeVar('X')
    Y = TypeVar('Y', Iterable[X])
    def filter(rule: Callable[[X], bool], input: Y) -> Y:
    ...

I think this could be written equivalently without having a constraint:

    from typing import Iterable
    X = TypeVar('X')
    def filter(rule: Callable[[X], bool], input: Iterable[X]) -> Iterable[X]:
    ...

Also, if this is similar to the `values` keyword argument to mypy's `typevar`, having a type variable with a single value would be equivalent to having a type alias (since subtypes are not valid), so the only interesting use cases would have 2 or more constraints.

There is actually no non-trivial example of using constraints in the PEP. I suggest adding an `AnyStr` example, as this seems like the most common use case for constraints (at least of the sort supported by mypy right now). Maybe the discussion should mention how this is different from bounded polymorphism/quantification as in Java, for example, as this is probably the most non-mainstream feature introduced in the PEP.

**Comment by brakhane** [comment]
Does that mean that there is no way to specify that two non union types must/will be the same? In the above example, I would have expected that the first filter function is guaranteed to return a file object if called with a file object, but the second definition could return a sequence instead.

That would be indeed unexpected and should be documented. It also seems inconsistent:

    X = TypeVar("X")
    def copy(original: X) -> X

    Y  = TypeVar("Y", Iterable[Y])
    def copy_it(original: Y) -> Y

Both declarations look identical, but while the first one will guarantee that isinstance(original, copy) is true, the second one doesn't; copy((1,2,3,4,5)) could return a list, for example.

**Comment by gvanrossum** [comment]
Yes, generic types and type variables need to be explained better. I think you did get the distinction between constrained and unconstrained type variables right (though your words are a bit confusing).

The best example of constrained type variables is AnyStr. See the explanation of this in http://mypy.readthedocs.org/en/latest/generics.html .

I would also like to point out that requiring a function to return an object of the exact same type as an argument is usually unreasonable, since being able to extract the type (e.g. `x.__class__`) is not sufficient to be able to create an instance. (How would you know the constructor signature?) There is some discussion of this in https://github.com/JukkaL/mypy/issues/539 (search for "Eugene").

**Comment by JukkaL** [comment]
Usually the only case where returning an object of the exactly same type as an argument is reasonable when the returned object *is* one of the arguments (or contained within an argument). So this is okay because we just pass through an object:

```
T = TypeVar('T')
def first(x: Sequence[T]) -> T: return x[0]
```

**Comment by vlasovskikh** [comment]
See also #1.

**Comment by JukkaL** [comment]
Rewrote the example.
