### ISSUE TITLE
Signal that a decorator implies `@no_type_check`

### ISSUE THREAD

**Issue by abarnert** [ambv/typehinting#51]
The idea is simple: some way to signal that a decorator implies `no_type_check`.

I'm not sure of the ideal syntax. Maybe it's no syntax at all: if `no_type_check` is automatically transitive through decorators, then if I define a top-level function with `@no_type_check` and then use that function (or a call of that function) as a decorator, the decorated function is also not type checked? But I don't know if that's too complex to require the type checker to handle.

The motivating example is frameworks that expose Python functions to other environments—wrap them up as CLI functions, or RPC server methods, or IRC bot handlers, or XMPP services, or whatever. Some of these frameworks (optionally) use annotations to express how command-line/service/etc. arguments get mapped to function parameters, and many more of them could. (The author of [`clize`](https://pypi.python.org/pypi/clize) just brought this up on python-ideas as an argument for opt-in instead of opt-out typing, but I don't think it's a very good argument for that; if anything, it's just an argument for making opt-out easier.)

There are two basic patterns for this: either you subclass some framework class and your methods are exposed, or you write regular functions and decorate them with `@clify.cli` or `@xrpc.service('spam.eggs')` or similar.

To handle the latter cases, instead of having to additionally decorate each of those functions as `@no_type_check` or mark the whole block of exposed functions with `# typing: OFF` or whatever, it would be nice to just decorate the decorator itself, in the framework, and then the users of the framework don't have to do anything at all.

**Comment by gvanrossum** [comment]
This is a reasonable thing to ask, and I recall a conversation about it before (but I cannot find it). I think there should be a meta-decorator that you set on a decorator to mean "this decorator turns off type checking for the decorated function". Because there are two kinds of decorators (@foo and @foo()), there may be some technical difficulties, but I think we can teach the type checker this. I don't think it's as easy as putting ``@no_type_check`` on the innermost function in the decorator definition though. We probably need a separate ``@meta_no_type_check`` to decorate the decorator definition's outermost function.

**Comment by gvanrossum** [comment]
I propose to add a new decorator named `@no_type_check_decorator`. Here's an implementation plus a code sample in the test: https://github.com/ambv/typehinting/commit/fc01f4cae88695336f36e15092f55114f37020a1

**Comment by gvanrossum** [comment]
Implemented in my typing.py and defined in the PEP.
