### ISSUE TITLE
Order of cast() arguments

### ISSUE THREAD

**Issue by gvanrossum** [ambv/typehinting#63]
There's a fair amount of of support on python-ideas for using `cast(x, T)` instead of `cast(T, x)`. IIRC this came up before. Not sure if this just reflects that it's an easy issue to have an opinion on. :-)

My own preference is for the arg order to mimic that of casts in C, C++ and Java (and probably many other languages); the counter-argument suggests analogy with `(x: T)` annotations as well as SQL's `CAST(foo AS type)`.

It's also been proposed to use `cast[T](x)`, but the argument against that is strong: too dense in punctuation, and two function calls instead of one, while `cast()` needs to be a fast no-op.

**Comment by The-Compiler** [comment]
For what it's worth, I also prefer `cast(x, T)`, since it's also the same order as in `isinstance(x, T)`.

I write a lot of C (and some C++), and I don't think the analogy from `(int)foo` to `cast(int, foo)` is very strong - `cast(...)` feels like a function call, `(int)foo` doesn't. I think if I were to implement a `cast`-function in C, I'd also use `cast(x, T)` because "cast x to type T" makes more sense to me as "cast to type T the object x".

**Comment by DavidMertz** [comment]
I opined on python-ideas as well.  The case for 'cast(x, T)' to me is simply that it reads like English, while the reverse order does not.  I.e. "Cast x to T" or "Cast x as T".  Moreover, there seems like a general (but not universal) convention in argument order is that the thing "operated on" comes first, and the "target" comes second.

**Comment by gvanrossum** [comment]
OTOH, Greg Ewing wrote:
```
I think that cast(T, x) is more readable when x is a long expression.
It puts the type next to the thing using or being assigned the result,
making it easier to visually verify that the types match up.
```

**Comment by amauryfa** [comment]
FYI, pypy's rpython uses `rffi.cast(T, x)`, and cffi as well: `ffi.cast("double", 42)`.
Yes, that's the same authors :-)

**Comment by gvanrossum** [comment]
I've decided, it will remain `cast(T, x)`. Reference: https://twitter.com/coates/status/587343718627287040
