### ISSUE TITLE
# type: comment for local variables defined in compound statement.

### ISSUE THREAD

**Issue by methane** [ambv/typehinting#73]
There is typing comment for simple assignment statement.
```python
# type of v is Foo
v = some_expression()  # type: Foo
```

But local variable may be defined in compound statements.

```
with expression() as x:

for x, y in expression():

{x. id: x for
 x in expression()}

from ._mod import x, y, z
```

Some of them are used very frequently in real world large applications. For example:

```python
# Django
for entry in Entry.objects.filter(author='foo').all():
    # type entry: Entry

# SQLAlchemy
for entry in session.query(Entry).filter_by(author='foo'):
    # type entry: Entry
```

Static type hinting is very helpful for such applications.
`entry = typing.Undefined(Entry)` can be used, but it reduce readability since it is mixed into normal codes.

Can we have handy way to typing them?

**Comment by gvanrossum** [comment]
Let's see what @JukkaL thinks.

Maybe any top-level statement that uniquely defines an assignment could have a `# type:` comment?  That would cover import, for, and with...as. (Though I'm not sure how this would cover importing multiple variables.)
```
from m import x  # type: int
for i in blargh():  # type: int
    ...
with fjool() as a:  # type: int
    ...
```
I don't think this will work for the dict comprehension (because the comprehension itself is presumably assigned to some variable), but I don't see that as an important use case anyway.

I don't think we should try to support `# type:` comments for sub-expressions -- the parsing would become *really* convoluted then, because there might potentially be a comment between any two tokens of an expression.

I don't really like variants like `# type x: int` because it means that more comments that weren't meant to be type declarations might accidentally be considered as such.

**Comment by vlasovskikh** [comment]
Adding comments to the same line as (local and global) assignment targets ([target](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-target) in the Python grammar that includes "with", "for", etc. targets; maybe + imported names) sounds good. For [target_list](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-target_list) we have multiple assignment comments #50.

**Comment by methane** [comment]
I see. Thanks for reply

**Comment by vlasovskikh** [comment]
@methane The idea hasn't been accepted or rejected, so you probably don't want to close the issue. At least I haven't figured it out for myself whether type comments for loop variables are allowed or not.

**Comment by methane** [comment]
OK.
Typing comment on separated line make it easier to keep 79 columns per line rule.
Following code looks a bit ugly.

```python
            for entry in session.query(xxx.YyyZzzEntry).filter(xxx.YyyZzzEntry.author='foo').limit(10): \
                    # type: Entry
                #...
```

**Comment by JukkaL** [comment]
I think it would be reasonable to support annotations for `for` and `with` targets. For multiple targets we can use #50, as @vlasovskikh pointed out.

I'm not sure about import statements. For many things we wouldn't be able to give precise types, including imported modules, classes and functions (as `Callable` only covers a subset of interesting callables). Also, stubs are meant to be used for modules -- there should probably be one obvious way to do it, and stubs are a better approach than annotating import statements.

**Comment by gvanrossum** [comment]
OK, let's do `for` and `with`, and recommend stubs for `import`.

Regarding the issue with comment on the long line, I have little sympathy. Having comments precede or follow the code they affect is too confusing. There are many strategies for rewriting long lines -- e.g. you could do
```
entries = session.query(xxx.YyyZzzEntry).filter(xxx.YyyZzzEntry.author='foo').limit(10)
for entry in entries:  # type: Entry
    ....
```

**Comment by methane** [comment]
Thanks!

**Comment by vlasovskikh** [comment]
Updated the PEP.
