### ISSUE TITLE
Encouraging experimentation with extensions

### ISSUE THREAD

**Issue by zooba** [ambv/typehinting#77]
I would like to see language in the PEP that encourages/authorizes libraries or tools to create extensions for type hints that may not be recognized by other tools. The PEP should remind developers that they will need stubs to allow other type checkers to complete without errors, but we don't need to give specific guidance on how to do this for the first release.

**Comment by vlasovskikh** [comment]
I guess experiments will continue anyway, since that's what we all have been doing. I don't feel we need a special extensions syntax for that, since we always can fall back to some form of decorators / docstrings / whatever and then work on a proposal for extending type annotations.

Nevertheless, addressing @zooba's issue, maybe we should allow any value that is neither a class nor a `typing.*` element to appear in annotations and be equivalent to `Any` by default so we could use these values for potential experiments with extending type annotations.

**Comment by gvanrossum** [comment]
I was sitting next to zooba (Steve Dower) when he entered this issue. I think his point is that experiments should not add new stuff to `typing.py` but add it to some other module which they control and for which they distribute a runtime implementation. They could then also distribute a stub for that module that redefines the various experimental things as type aliases for `Any` for the benefit of other type checkers. (Their own type checker would not use that stub of course.)

**Comment by zooba** [comment]
I'm not entirely sure how to define something that is "[not] a class" in Python, but Guido's approach sounds fine to me. I'd expect code to look like:

```python
from typing import *
from mytypechecker.extensions import *

def f(x : MyExtension):
    pass
```

Where `mytypechecker/extensions.py` defines `MyExtension = typing.Any` to satisfy other typecheckers. Then when running `mytypechecker` it has a built-in understanding of how to process its extensions rather than looking at the source.

If that's acceptable, then I guess all I'm asking is that it be formalised as "this is how to do it" rather than it becoming assumed knowledge that you can only find out by lurking on a mailing list.

**Comment by gvanrossum** [comment]
I don't think we need to add explicit language to the PEP. Let 1000 flowers bloom!
