### ISSUE TITLE
What's the type of memoryviews?

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#83]
Do we just use `memoryview`, or should it also know about dimensions, item sizes/types, etc.?

**Comment by gvanrossum** [comment]
Until this morning I didn't know about them either. :-)

I'd like to start by somehow unifying bytes, bytearray, memoryview under one of the two branches of AnyStr.

**Comment by JukkaL** [comment]
Okay, it seems that `memoryview` is generally valid if a C function expects a `bytes` argument, based on a few random examples that I tried. However, `memoryview` doesn't support most of the methods supported by `bytes` (string operations). This means that `memoryview` is *not* generally valid as a `bytes` alternative for Python functions.

We have at least two options to move forward, with different tradeoffs:

1. We could make `memoryview` a (special, hard-coded) subtype of `bytes`, similar to `bytearray` and `int`/`float`. This could result in type errors in code that uses things like `replace` or `startswith`, but `memoryview` would interoperate nicely with `AnyStr` (it would get promoted to `bytes`, and valid everywhere `AnyStr` is used). However, if a function that uses `AnyStr` actually returns a `memoryview`, the return type would be unexpected (`bytes`) due to the promotion.

2. We could update stubs to use `Union[bytes, memoryview]` (or a type alias with this value) everywhere where `memoryview` is valid. This probably includes most methods of `bytes` and `write`, at least. This would imply a lot of stub changes. The bad thing is that `memoryview` would not be valid for arguments of type `AnyStr`, even though some of these functions actually accept `memoryview` objects (such as `re.match`). Including `memoryview` in `AnyStr` or having an alternative to `AnyStr` with `memoryview` would have issues as well (I can elaborate on these if somebody is interested).

Summary: It's tricky to support `memoryview` correctly in all contexts. Option 1 would be easier to implement (local change) and would have less dramatic effect on stubs, so it would probably be a safer option. I don't see a lot of uses of `memoryview` in the code that I read or write so it probably doesn't warrant invasive changes.

**Comment by gvanrossum** [comment]
Agreed, option 1 sounds fine. I personally am aware of two uses for memoryview:

- NumPy may use memoryview to represent arrays, though it's also possible that it uses its own C API for this purpose. Maybe you can find someone at the sprints who knows?

- I recall seeing highly optimized code in Twisted that was using the PY2 equivalent (buffer()) to create a sliding window over a really large buffer (like 64 MB) that was being sent through a socket. The idea is that you always call send() with the entire rest of the buffer, and you bump the start of the buffer by however many bytes send() actually reports that it wrote. If send() actually writes fairly small blocks (e.g. 128 KB) that algorithm would become quadratic when implemented using regular (copying) slices. (I discovered this because an early attempt at porting Twisted to PY3 had such a quadratic bug.)

**Comment by gvanrossum** [comment]
So let's do (1) and mention this in the PEP (also int/float needs to be mentioned).
